export const nfts = [
    {
        id: 1,
        title: 'Angry Agatsuma',
        artist: 'Koyoharu Gotouge',
        price: 170,
        image: '/NFTs/trial.jpg',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "A fiery thunderclap of rage and power.",

      },
      {
        id: 2,
        title: "Rock'n Ride",
        artist: 'Hajime Maste',
        price: 95,
        image: '/NFTs/trial3.jpg',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "A vibrant adventure of speed and sound.",

      },
      {
        id: 3,
        title: 'Toneless Inumaki',
        artist: 'Gege Akutami',
        price: 125,
        image: '/NFTs/trial2.jpg',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "A silent curse with a hidden voice.",

      },
      {
        id: 4,
        title: 'Lonesome Titan',
        artist: 'Nana Yamada',
        price: 480,
        image: '/NFTs/eren2.jpg',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "A tragic hero with a monstrous fate.",

      },
      {
        id: 5,
        title: 'Anti-magic Brat',
        artist: 'Yūki Tabata',
        price: 300,
        image: '/NFTs/asta1.png',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "The cursed child who defies fate with his sword",

      },
      {
        id: 6,
        title: 'Winged Wonders',
        artist: 'Yumi Nakamura',
        price: 450,
        image: '/NFTs/bird.jpg',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "Soar high with these rare and powerful creatures.",

      },
      {
        id: 7,
        title: 'Bubbly Fun',
        artist: 'Mio Watanabe',
        price: 250,
        image: '/NFTs/bubble.png',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "Meet the happiest and squishiest friend you’ll ever have",

      },
      {
        id: 8,
        title: 'Scaling Heights',
        artist: 'Saki Kobayashi',
        price: 480,
        image: '/NFTs/climb.png',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "A vibrant and agile reptile that loves to explore new heights.",

      },
      {
        id: 9,
        title: 'Ethereal Vision',
        artist: 'Yuji Ito',
        price: 350,
        image: '/NFTs/Eth.jpg',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "The symbol of a decentralized and innovative future.",

      },
      {
        id: 10,
        title: 'Flaming Fury',
        artist: 'Kei Tanaka',
        price: 500,
        image: '/NFTs/mega.jpg',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "When a fiery dragon unleashes its wrath",

      },
      {
        id: 11,
        title: 'Golden Ride',
        artist: 'ArtChen',
        price: 450,
        image: '/NFTs/goldskate.png',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "",

      },
      {
        id: 12,
        title: 'Sonic Spectrum',
        artist: 'KryptoKanbasu',
        price: 400,
        image: '/NFTs/splash.png',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "A rainbow of sound vibrations.",

      },
      {
        id: 13,
        title: 'Harmony',
        artist: 'Zara Star',
        price: 100,
        image: '/NFTs/symphony.jpg',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "A symphony of colors harmonizing on a captivating canvas.",

      },
      {
        id: 14,
        title: 'Lunar Mice',
        artist: 'Leo Lee',
        price: 200,
        image: '/NFTs/yearofmice.png',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "Whiskers that trace ancient tales of lunar legend.",

      },
      {
        id: 15,
        title: 'Duality of Fate',
        artist: 'Mia Moon',
        price: 150,
        image: '/NFTs/twoface.png',
        owner: "0x1234...",
        views: 1200,
        favorites: 350,
        description: "Two faces, two destinies, one choice",

      },
    // Add more NFT objects here...
  ];
  
  export const gifs = [
    {
      id: 1,
      title: "Squirtle Squad",
      artist: "Taro Yamamoto",
      price: 350,
      image: "/NFTs/squirtle.gif",
      owner: "0x1234...",
      views: 1200,
      favorites: 350,
      description: "",
    },
    {
      id: 2,
      title: "The Giant Night",
      artist: "Jotaro",
      price: 440,
      image: "/NFTs/sword.gif",
      owner: "0x1234...",
      views: 1200,
      favorites: 350,
      description: "",
    },
    {
      id: 3,
      title: "Water Dragon’s Stance",
      artist: "Sora Tanaka",
      price: 675,
      image: "/NFTs/kamado.gif",
      owner: "0x1234...",
      views: 1200,
      favorites: 350,
      description: "In the depths, a dragon's grace ignites the flowing currents.",
    },
    {
      id: 4,
      title: "Quantum Connections",
      artist: "TKei Yamada",
      price: 945,
      image: "/NFTs/network.gif",
      owner: "0x1234...",
      views: 1200,
      favorites: 350,
      description: " A mesmerizing journey through the fabric of reality",
    },
    {
      id: 5,
      title: "Circular Logic",
      artist: "Mika Nakajima",
      price: 610,
      image: "/NFTs/dazzling.gif",
      owner: "0x1234...",
      views: 1200,
      favorites: 350,
      description: "Where thoughts intertwine, spiraling through infinite possibilities",
    },
    {
      id: 6,
      title: "Blaze of Glory",
      artist: "Ryo Suzuki",
      price: 780,
      image: "/NFTs/firei.gif",
      owner: "0x1234...",
      views: 1200,
      favorites: 350,
      description: "",
    },
    {
      id: 7,
      title: "Oceanic Dreams",
      artist: "Akira Sato",
      price: 465,
      image: "/NFTs/deepblue.gif",
      owner: "0x1234...",
      views: 1200,
      favorites: 350,
      description: "",
    },
    {
      id: 8,
      title: "Luminous Growth",
      artist: "Milo Moon",
      price: 320,
      image: "/NFTs/thestart.gif",
      owner: "0x1234...",
      views: 1200,
      favorites: 350,
      description: "From humble roots, a radiant tree blossoms towards the heavens.",
    },
  ];

  export const collection = [
    {
      name: "SYDUKS",
      status: "Live",
      floorPrice: "0.37 ETH",
      volume: "0.91 ETH",
      image: "./galaxyNFT.png",
    },
    {
      name: "Bored Ape Yacht Club",
      status: "Minted",
      floorPrice: "46.50 ETH",
      volume: "265.1 ETH",
      image: "./NFTs/bored.png",
    },
    {
      name: "Pudgy Penguins",
      status: "Revealed",
      floorPrice: "0.07 ETH",
      volume: "2.5 ETH",
      image: "./NFTs/penguin.png",
    },
    {
      name: "The CaptainZ",
      status: "Live",
      floorPrice: "0.91 ETH",
      volume: "12.2 ETH",
      image: "./NFTs/Eth.jpg",
    },
    {
      name: "Them Jordans",
      status: "Revealing",
      floorPrice: "9.8 ETH",
      volume: "50.68 ETH",
      image: "./NFTs/jordans.jpg",
    },
    {
      name: "PixelMon",
      status: "Ready",
      floorPrice: "3 ETH",
      volume: "22.09 ETH",
      image: "./NFTs/bird.jpg",
    },
    {
      name: "Hv-MTL",
      status: "Paused",
      floorPrice: "0.06 ETH",
      volume: "10.01 ETH",
      image: "./NFTs/climb.png",
    },
  ];

  export const featuredSellers = [
    {
      id: 1,
      username: 'Zara Zee',
      profileImage: '/Avatar/Avatar1.jpg',
      tagline: 'Digital art with a twist of surrealism',
      topSellingNFTs: [
        {
          id: 1,
          title: 'Yin-Yang',
          soldfor: 450,
          image: '/yinyang.gif',
          owner: "0x1234...",
          views: 1200,
          favorites: 35,
          description: "",
        },
        {
          id: 2,
          title: 'Submerged',
          soldfor: 100,
          image: '/yellow.png',
          owner: "0x1234...",
          views: 1200,
          favorites: 35,
          description: "",
        },
      ],
    },
    {
      id: 2,
      username: 'Milo Moon',
      profileImage: '/Avatar/golden.png',
      tagline: 'Exploring the cosmos through pixel art',
      topSellingNFTs: [
        {
          id: 3,
          title: 'Pixel Ape',
          soldfor: 220,
          image: '/NFTs/apepixel.png',
          owner: "0x1234...",
          views: 1200,
          favorites: 35,
          description: "",
        },
        {
          id: 4,
          title: 'Cosmic Pixels',
          soldfor: 130,
          image: '/NFTs/pixelspace.png',
          owner: "0x1234...",
          views: 1200,
          favorites: 35,
          description: "",
        },
      ],
    },
    {
        id: 3,
        username: 'Hangetsu',
        profileImage: '/Avatar/Her.jpg',
        tagline: 'Mixing music and visuals in immersive NFTs',
        topSellingNFTs: [
          {
            id: 5,
            title: 'Luminous Growth',
            soldfor: 425 ,
            image: '/NFTs/thestart.gif',
            owner: "0x1234...",
            views: 1200,
            favorites: 350,
            description: "",
          },
          {
            id: 6,
            title: 'Immersive',
            soldfor: 90 ,
            image: '/NFTs/music.png',
            owner: "0x1234...",
            views: 1200,
            favorites: 350,
            description: "",
          },
        ],
      },
  ];
